//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltraStarDeluxeEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UltraStarDeluxeEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Cover Image.
        /// </summary>
        internal static string coverDeleteCaption {
            get {
                return ResourceManager.GetString("coverDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Deletion Error.
        /// </summary>
        internal static string coverDeleteErrorCaption {
            get {
                return ResourceManager.GetString("coverDeleteErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while deleting the cover image..
        /// </summary>
        internal static string coverDeleteErrorMessage {
            get {
                return ResourceManager.GetString("coverDeleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete the cover image?
        ///This will also delete the image file from your drive..
        /// </summary>
        internal static string coverDeleteMessage {
            get {
                return ResourceManager.GetString("coverDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Download Error.
        /// </summary>
        internal static string coverDownloadErrorCaption {
            get {
                return ResourceManager.GetString("coverDownloadErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while downloading the new cover image. Make sure that the URL leads to an image in JPG or PNG format..
        /// </summary>
        internal static string coverDownloadErrorMessage {
            get {
                return ResourceManager.GetString("coverDownloadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Cover Image from URL.
        /// </summary>
        internal static string coverDownloadFromUrl {
            get {
                return ResourceManager.GetString("coverDownloadFromUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover successfully downloaded..
        /// </summary>
        internal static string coverDownloadSuccessMessage {
            get {
                return ResourceManager.GetString("coverDownloadSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the URL of the image you want to download as the new cover..
        /// </summary>
        internal static string coverDownloadUrlInputMessage {
            get {
                return ResourceManager.GetString("coverDownloadUrlInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite Cover.
        /// </summary>
        internal static string coverOverwriteCaption {
            get {
                return ResourceManager.GetString("coverOverwriteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to set a new cover image? This will delete the old one after saving..
        /// </summary>
        internal static string coverOverwriteMessage {
            get {
                return ResourceManager.GetString("coverOverwriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Cover Image.
        /// </summary>
        internal static string coverSelectFileCaption {
            get {
                return ResourceManager.GetString("coverSelectFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string errorCaption {
            get {
                return ResourceManager.GetString("errorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to save the song before exporting it. Do you want to do this now?.
        /// </summary>
        internal static string exportSongSaveFirstMessage {
            get {
                return ResourceManager.GetString("exportSongSaveFirstMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose export destination.
        /// </summary>
        internal static string exportSongTitle {
            get {
                return ResourceManager.GetString("exportSongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the folder of your UltraStar Deluxe installation..
        /// </summary>
        internal static string findUsdFolderDescription {
            get {
                return ResourceManager.GetString("findUsdFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPG or PNG|*.jpg;*.jpeg;*.png.
        /// </summary>
        internal static string imageFileFilter {
            get {
                return ResourceManager.GetString("imageFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MP3 file doesn&apos;t exist..
        /// </summary>
        internal static string mp3FileNotExistsWarningIcon {
            get {
                return ResourceManager.GetString("mp3FileNotExistsWarningIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite File.
        /// </summary>
        internal static string overwriteFileCaption {
            get {
                return ResourceManager.GetString("overwriteFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file already exists. Do you want to overwrite it?.
        /// </summary>
        internal static string overwriteFileMessage {
            get {
                return ResourceManager.GetString("overwriteFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Song.
        /// </summary>
        internal static string reloadSongCaption {
            get {
                return ResourceManager.GetString("reloadSongCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured while reloading{0}!.
        /// </summary>
        internal static string reloadSongErrorMessage {
            get {
                return ResourceManager.GetString("reloadSongErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The song couldn&apos;t be reloaded due to the file {0} not existing..
        /// </summary>
        internal static string reloadSongFileNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("reloadSongFileNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to reload the selected song?
        ///Unsaved changes will be lost..
        /// </summary>
        internal static string reloadSongMessage {
            get {
                return ResourceManager.GetString("reloadSongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Songs.
        /// </summary>
        internal static string reloadSongsCaption {
            get {
                return ResourceManager.GetString("reloadSongsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to reload all songs from the song directories? Unsaved changes will be lost..
        /// </summary>
        internal static string reloadSongsMessage {
            get {
                return ResourceManager.GetString("reloadSongsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; was reloaded successfully..
        /// </summary>
        internal static string reloadSongSuccessMessage {
            get {
                return ResourceManager.GetString("reloadSongSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Song.
        /// </summary>
        internal static string saveSongCaption {
            get {
                return ResourceManager.GetString("saveSongCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured while trying to save the song{0}..
        /// </summary>
        internal static string saveSongErrorMessage {
            get {
                return ResourceManager.GetString("saveSongErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songlist Initialization Done.
        /// </summary>
        internal static string songListInitializationDoneCaption {
            get {
                return ResourceManager.GetString("songListInitializationDoneCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} valid UltraStar songs where found..
        /// </summary>
        internal static string songListInitializationDoneMessage {
            get {
                return ResourceManager.GetString("songListInitializationDoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} invalid song files where found:
        ///{1}.
        /// </summary>
        internal static string songListInitializationErrorsMessage {
            get {
                return ResourceManager.GetString("songListInitializationErrorsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song not playable.
        /// </summary>
        internal static string songNotPlayableCaption {
            get {
                return ResourceManager.GetString("songNotPlayableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The song you&apos;re trying to save is currently not playable. Are you sure that you want to save it?.
        /// </summary>
        internal static string songNotPlayableMessage {
            get {
                return ResourceManager.GetString("songNotPlayableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the songs you&apos;re trying to save is currently not playable. Are you sure that you want to save?.
        /// </summary>
        internal static string songsNotPlayableMessage {
            get {
                return ResourceManager.GetString("songsNotPlayableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string successCaption {
            get {
                return ResourceManager.GetString("successCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text File|*.txt.
        /// </summary>
        internal static string textFileFilter {
            get {
                return ResourceManager.GetString("textFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Changes.
        /// </summary>
        internal static string unsavedChangesCaption {
            get {
                return ResourceManager.GetString("unsavedChangesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Do you want to save all changes before closing?.
        /// </summary>
        internal static string unsavedChangesMessage {
            get {
                return ResourceManager.GetString("unsavedChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter URL.
        /// </summary>
        internal static string urlInputCaption {
            get {
                return ResourceManager.GetString("urlInputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No UltraStar Directory.
        /// </summary>
        internal static string usdPathNotConfiguredCaption {
            get {
                return ResourceManager.GetString("usdPathNotConfiguredCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no UltraStar path configured at the moment.
        ///Please select your UltraStar Deluxe directory in order to move on..
        /// </summary>
        internal static string usdPathNotConfiguredMessage {
            get {
                return ResourceManager.GetString("usdPathNotConfiguredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UltraStar directory not valid.
        /// </summary>
        internal static string usdPathNotValidCaption {
            get {
                return ResourceManager.GetString("usdPathNotValidCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder you selected isn&apos;t an UltraStar Directory.
        ///Please select another one..
        /// </summary>
        internal static string usdPathNotValidMessage {
            get {
                return ResourceManager.GetString("usdPathNotValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The video file doesn&apos;t exist..
        /// </summary>
        internal static string videoFileNotExistsWarningIcon {
            get {
                return ResourceManager.GetString("videoFileNotExistsWarningIcon", resourceCulture);
            }
        }
    }
}
